"""
文物初始数据导入脚本

从 ArkTS 前端的 MockArtworks 数据导入 MySQL 数据库。
运行方式： python scripts/seed_data.py
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from datetime import datetime
from app.database import SessionLocal, engine, Base
from app.models.artwork import Artwork, ArtworkImage, AudioGuide
from app.models.user import User
from app.utils.auth import hash_password


def seed_artworks():
    """导入文物数据（与 MockArtworks.ets 一一对应）"""
    artworks_data = [
        {
            "id": "por_001",
            "name": "元青花缠枝牡丹纹梅瓶",
            "dynasty": "元",
            "type": "青花瓷",
            "material": "瓷",
            "description": "元代青花瓷珍品，器型挺拔，纹饰繁复精美，青花发色浓艳。",
            "detail_description": "此元代青花缠枝牡丹纹梅瓶，小口、短颈、丰肩、瘦底、圈足，造型优美挺拔。通体绘青花缠枝牡丹纹，"牡丹"花大色艳，有"花中之王"之美誉。青花色泽浓艳深沉，具有典型的元青花"至正型"特征。纹饰布局繁密而不乱，层次丰富，是元青花瓷器中的杰出代表。",
            "cover_image": "https://example.com/porcelain/por_001_0_full.jpg",
            "popularity": 9850,
            "year_range": "14世纪",
            "origin": "江西景德镇",
            "dimensions": "高48.5cm，口径5.2cm，底径14.2cm",
            "weight": "约5.8kg",
            "collection_place": "北京故宫博物院",
            "tags": ["元青花", "梅瓶", "牡丹纹", "缠枝纹", "景德镇"],
            "historical_background": "元代是中国青花瓷发展的黄金时期。元青花以其独特的钴料发色和繁复的纹饰著称于世。元朝在景德镇设立浮梁瓷局，推动了青花瓷技术的成熟。此类梅瓶在元代多用作酒器或陈设瓷，是元代对外贸易的重要商品之一，远销中东、欧洲等地。",
            "cultural_significance": "元青花在中国陶瓷史上具有里程碑意义，它开创了中国陶瓷的青花时代，对后世青花瓷发展产生了深远影响。其钴料来自波斯（今伊朗地区），体现了元代中西文化交流的盛况。2005年，一件元青花鬼谷子下山图罐在伦敦佳士得拍出约2.3亿元人民币天价，创下了当时中国艺术品拍卖的世界纪录。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 300,
        },
        {
            "id": "por_002",
            "name": "清乾隆粉彩百鹿图尊",
            "dynasty": "清",
            "type": "粉彩",
            "material": "瓷",
            "description": "乾隆粉彩瓷精品，器身绘百鹿图，寓意吉祥，色彩柔和绚丽。",
            "detail_description": "清乾隆粉彩百鹿图尊，撇口、粗颈、圆腹、圈足。器身以粉彩绘制百鹿图，山林间群鹿或奔跑、或嬉戏、或觅食、或小憩，姿态各异，生动传神。"百鹿"谐音"百禄"，寓意富贵吉祥。粉彩色彩柔和淡雅，层次丰富，充分展现了乾隆时期粉彩瓷器的最高水平。底足有"大清乾隆年制"六字三行篆书款。",
            "cover_image": "https://example.com/porcelain/por_002_1_full.jpg",
            "popularity": 9200,
            "year_range": "1736-1795",
            "origin": "江西景德镇",
            "dimensions": "高62.5cm，口径18.8cm，底径22.5cm",
            "weight": "约12.3kg",
            "collection_place": "北京故宫博物院",
            "tags": ["清乾隆", "粉彩", "百鹿图", "尊", "景德镇"],
            "historical_background": "粉彩是清代康熙晚期在珐琅彩影响下创制的釉上彩瓷新品种，雍正、乾隆时期达到鼎盛。乾隆皇帝酷爱艺术，尤其热衷瓷器，常亲自参与瓷器样式设计。粉彩百鹿图尊是乾隆时期的典型陈设瓷，展现了宫廷绘画与瓷器工艺的完美结合。",
            "cultural_significance": "粉彩瓷是中国陶瓷史上的重要创新，它融合了中国传统绘画技法与西方珐琅彩工艺，形成了独特的艺术风格。百鹿图尊不仅是一件精美的艺术品，更承载了丰富的文化寓意，是研究清代社会文化、审美趣味的重要实物资料。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 280,
        },
        {
            "id": "por_003",
            "name": "宋汝窑天青釉弦纹樽",
            "dynasty": "宋",
            "type": "青瓷",
            "material": "瓷",
            "description": "汝窑瓷器的典范，天青釉色温润如玉，开片纹理自然天成。",
            "detail_description": "宋汝窑天青釉弦纹樽，直口、平底、圈足外撇。器身饰三组弦纹，造型简洁端庄，线条挺拔有力。釉色天青，釉面匀净滋润，开细碎片纹，"蟹爪纹"清晰可见。汝窑瓷器以其"天青釉"闻名，釉色如雨过天晴般清新雅致。此樽为汝官窑典型器物，是宋代宫廷祭祀用器。",
            "cover_image": "https://example.com/porcelain/por_003_0_full.jpg",
            "popularity": 8800,
            "year_range": "1086-1125",
            "origin": "河南宝丰清凉寺",
            "dimensions": "高12.8cm，口径18.2cm，底径12.5cm",
            "weight": "约1.2kg",
            "collection_place": "北京故宫博物院",
            "tags": ["汝窑", "天青釉", "弦纹", "樽", "宋代五大名窑"],
            "historical_background": "汝窑为宋代五大名窑之首，北宋晚期为宫廷烧造御用瓷器，烧造时间仅约20年。汝官窑遗址位于今河南省宝丰县清凉寺村。汝窑瓷器以玛瑙入釉，釉色以天青为贵，釉面温润如玉，开片纹理丰富，有"蝉翼纹"、"蟹爪纹"、"鱼子纹"等。",
            "cultural_significance": "汝窑瓷器以其"似玉非玉而胜似玉"的质感，被誉为"宋瓷之冠"。传世汝窑瓷器不足百件，每一件都是稀世珍宝。2017年，一件汝窑天青釉洗在香港苏富比拍出2.94亿港元天价。汝窑代表了宋代单色釉瓷器审美的最高境界，体现了宋代"格物致知"的哲学思想。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 350,
        },
        {
            "id": "por_004",
            "name": "明成化斗彩鸡缸杯",
            "dynasty": "明",
            "type": "斗彩",
            "material": "瓷",
            "description": "成化斗彩名品，鸡缸杯小巧玲珑，画面生动活泼，色彩明丽。",
            "detail_description": "明成化斗彩鸡缸杯，敞口、浅腹、卧足，造型小巧玲珑。杯身绘有子母鸡群觅食于山石花草间的场景，雄鸡昂首啼鸣，母鸡带领小鸡觅食，画面温馨生动。斗彩工艺精湛，青花勾线后填彩，色彩丰富明丽，有红、黄、绿、紫等多种颜色。底足有"大明成化年制"六字双行楷书款。",
            "cover_image": "https://example.com/porcelain/por_004_0_full.jpg",
            "popularity": 9500,
            "year_range": "1465-1487",
            "origin": "江西景德镇",
            "dimensions": "高3.8cm，口径8.3cm，足径4.5cm",
            "weight": "约0.2kg",
            "collection_place": "北京故宫博物院",
            "tags": ["明成化", "斗彩", "鸡缸杯", "成化窑"],
            "historical_background": "斗彩是明代成化时期创烧的釉上彩瓷品种，先用青花在釉下勾勒纹饰轮廓，入窑烧制后再在釉上填彩二次烧成。成化皇帝对瓷器极为讲究，御窑厂产量有限但质量精绝。鸡缸杯是成化斗彩中最负盛名的品种，据说成化皇帝为取悦万贵妃而命人特制。",
            "cultural_significance": "成化斗彩鸡缸杯在中国陶瓷史上地位极高，被誉为"瓷中极品"。2014年，一件玫茵堂藏成化斗彩鸡缸杯在香港苏富比以2.81亿港元成交，刷新了中国瓷器拍卖纪录，反映了其无与伦比的艺术价值和收藏价值。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 260,
        },
        {
            "id": "por_005",
            "name": "清康熙郎窑红釉观音瓶",
            "dynasty": "清",
            "type": "色釉瓷",
            "material": "瓷",
            "description": "郎窑红釉瓷器的典范，釉色鲜红如牛血，"脱口垂足"特征明显。",
            "detail_description": "清康熙郎窑红釉观音瓶，撇口、短颈、丰肩、修腹、撇足，形似观音菩萨所持净瓶，故称"观音瓶"。釉色鲜红浓艳，如初凝牛血，釉面玻璃质感强，有细小的开片。口部因釉层较薄而呈浅红色或白色，俗称"脱口"；底部边缘釉色垂流，形成"垂足"现象。康熙郎窑红为江西巡抚郎廷极督窑所创，代表了清代红釉瓷器的最高水平。",
            "cover_image": "https://example.com/porcelain/por_005_1_full.jpg",
            "popularity": 7500,
            "year_range": "1662-1722",
            "origin": "江西景德镇",
            "dimensions": "高46.5cm，口径12.8cm，底径14.2cm",
            "weight": "约4.5kg",
            "collection_place": "上海博物馆",
            "tags": ["郎窑红", "康熙", "观音瓶", "红釉", "景德镇"],
            "historical_background": "郎窑红是清代康熙时期仿明代宣德红釉的创新品种。督陶官郎廷极在景德镇御窑厂督造瓷器，成功烧制出这一名贵色釉。郎窑红的烧制难度极大，对窑温、气氛要求极为严格，"要想穷，烧郎红"的民谚反映了其烧造之难。",
            "cultural_significance": "郎窑红釉是中国红釉瓷器的杰出代表，其色泽之浓艳、质感之华美令后世叹为观止。它继承并超越了明代的红釉工艺，为雍正、乾隆时期颜色釉瓷器的繁荣奠定了技术基础。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 240,
        },
        {
            "id": "por_006",
            "name": "清雍正霁蓝釉天球瓶",
            "dynasty": "清",
            "type": "色釉瓷",
            "material": "瓷",
            "description": "雍正霁蓝釉精品，釉色深沉如蓝宝石，造型浑圆大气。",
            "detail_description": "清雍正霁蓝釉天球瓶，直口、长颈、球形腹、圈足，因腹部浑圆似天球而得名。通体施霁蓝釉，釉色匀净深沉，如蓝宝石般晶莹剔透，釉面满布细小的棕眼。霁蓝釉为霁红釉的姊妹品种，同样采用高温一次烧成。雍正时期霁蓝釉色泽最为纯正，达到了"蓝如深海"的艺术效果。底部有"大清雍正年制"六字双行楷书款。",
            "cover_image": "https://example.com/porcelain/por_006_0_full.jpg",
            "popularity": 6800,
            "year_range": "1723-1735",
            "origin": "江西景德镇",
            "dimensions": "高55.8cm，口径11.2cm，底径17.5cm",
            "weight": "约7.2kg",
            "collection_place": "北京故宫博物院",
            "tags": ["霁蓝釉", "雍正", "天球瓶", "蓝釉", "景德镇"],
            "historical_background": "霁蓝釉又称"祭蓝釉"、"积蓝釉"，是一种高温石灰碱釉。元代开始烧造，明清时期达到鼎盛。雍正皇帝对瓷器有极高的审美要求，霁蓝釉天球瓶正是这一时期官窑的代表作品。",
            "cultural_significance": "雍正霁蓝釉瓷器以其纯净的蓝色和高雅的造型，展现了清代宫廷审美的极致追求。天球瓶作为明清宫廷的重要陈设器，其庄重典雅的风格影响深远，至今仍是传统陶瓷艺术的经典器型。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 220,
        },
        {
            "id": "por_007",
            "name": "清乾隆茶叶末釉绶带耳瓶",
            "dynasty": "清",
            "type": "色釉瓷",
            "material": "瓷",
            "description": "茶叶末釉为铁结晶釉名品，釉色黄绿相间如茶叶细末，古朴雅致。",
            "detail_description": "清乾隆茶叶末釉绶带耳瓶，盘口、束颈、颈部两侧饰绶带形耳、圆腹、圈足。通体施茶叶末釉，釉色呈鳝鱼黄绿色，釉面布满细小的黄褐色结晶斑点，如茶叶细末散布其中。茶叶末釉属于铁结晶釉的一种，需在高温下使铁元素形成结晶析出，对窑温控制要求极高。",
            "cover_image": "https://example.com/porcelain/por_007_0_full.jpg",
            "popularity": 5500,
            "year_range": "1736-1795",
            "origin": "江西景德镇",
            "dimensions": "高38.5cm，口径10.2cm，底径13.8cm",
            "weight": "约3.8kg",
            "collection_place": "南京博物院",
            "tags": ["茶叶末釉", "乾隆", "绶带耳瓶", "结晶釉", "景德镇"],
            "historical_background": "茶叶末釉最早见于唐代耀州窑，清代雍正、乾隆时期达到工艺巅峰。唐英《陶成纪事碑》中记载了茶叶末釉的配方和烧制工艺。该釉色因烧成气氛不同可呈现鳝鱼黄、蟹甲青、蛇皮绿等多种色调。",
            "cultural_significance": "茶叶末釉以其含蓄内敛的美感，在清代颜色釉瓷器中独树一帜，体现了中国传统审美中崇尚自然、追求质朴的哲学思想，备受文人雅士推崇。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 200,
        },
        {
            "id": "por_008",
            "name": "明万历五彩龙凤纹笔盒",
            "dynasty": "明",
            "type": "五彩",
            "material": "瓷",
            "description": "万历五彩瓷精品，色彩艳丽，龙凤纹饰富丽堂皇。",
            "detail_description": "明万历五彩龙凤纹笔盒，长方形，子母口，圈足。盒盖与盒身均以五彩绘龙凤穿花纹，盖面正中为龙凤呈祥图案，周围饰以缠枝花卉。五彩以红、黄、绿、紫、蓝等色彩为主，色彩浓艳热烈，对比强烈。万历五彩素有"大红大绿"之称，是明代晚期最具代表性的瓷器品种之一。",
            "cover_image": "https://example.com/porcelain/por_008_0_full.jpg",
            "popularity": 7200,
            "year_range": "1573-1620",
            "origin": "江西景德镇",
            "dimensions": "长28.5cm，宽18.2cm，高10.5cm",
            "weight": "约2.8kg",
            "collection_place": "北京故宫博物院",
            "tags": ["明万历", "五彩", "龙凤纹", "笔盒", "景德镇"],
            "historical_background": "五彩是明代景德镇创烧的釉上彩瓷品种，嘉靖、万历时期最为盛行。万历皇帝在位48年，御窑厂生产了大量五彩瓷，主要用于宫廷日用和陈设。五彩瓷色彩饱和度高，装饰风格热烈奔放，反映了明晚期的审美趣味。",
            "cultural_significance": "万历五彩瓷器以其独特的艺术风格在中国陶瓷史上占有重要地位，对清代康熙五彩有直接影响。其鲜明的色彩和丰富的纹饰不仅受到国内市场的欢迎，还大量出口到欧洲，对西方陶瓷艺术产生了深远影响。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 260,
        },
        {
            "id": "por_009",
            "name": "清雍正珐琅彩松竹梅纹瓶",
            "dynasty": "清",
            "type": "珐琅彩",
            "material": "瓷",
            "description": "珐琅彩瓷至尊，雍正御制，松竹梅岁寒三友图，诗书画印合一。",
            "detail_description": "清雍正珐琅彩松竹梅纹瓶，撇口、细颈、垂腹、圈足。器身以珐琅彩绘松竹梅"岁寒三友"图，松树苍劲，翠竹挺拔，梅花傲雪，画工精绝。珐琅彩色彩丰富，层次分明，具有油画般的立体效果。瓶身配有雍正皇帝御题诗句，诗书画印相结合，是宫廷艺术的巅峰之作。",
            "cover_image": "https://example.com/porcelain/por_009_0_full.jpg",
            "popularity": 8900,
            "year_range": "1723-1735",
            "origin": "江西景德镇（内廷造办处彩绘）",
            "dimensions": "高22.5cm，口径5.8cm，底径7.2cm",
            "weight": "约1.1kg",
            "collection_place": "台北故宫博物院",
            "tags": ["珐琅彩", "雍正", "松竹梅", "岁寒三友", "御制"],
            "historical_background": "珐琅彩瓷是清代康熙晚期在宫廷内务府造办处珐琅作创制的一种瓷器新品种。雍正时期珐琅彩工艺达到顶峰，胎体精选景德镇御窑厂最优质的素白瓷器，送入宫内由宫廷画师在造办处完成彩绘和烧制。珐琅彩瓷的颜料含有硼、砷等成分，色彩绚丽，品种稀少。",
            "cultural_significance": "珐琅彩瓷被誉为"官窑中的官窑"，是清代宫廷瓷器中最为名贵的品种。其制作过程由皇帝直接过问，产量极少，传世品不过数百件，每一件都是珍稀的艺术瑰宝。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 320,
        },
        {
            "id": "por_010",
            "name": "宋汝窑三足奁",
            "dynasty": "宋",
            "type": "青瓷",
            "material": "瓷",
            "description": "北宋汝官窑典型器，天青釉面温润如玉，三足造型古朴庄重。",
            "detail_description": "宋汝窑三足奁，直口、平底、下承三足。器身呈筒形，外壁饰三组弦纹。通体施天青釉，釉色幽玄静谧，釉面满布细密的开片纹理。胎体呈香灰色，胎质细腻。三足奁为汉代以来传统的盛器造型，宋代汝官窑将其升华为高雅的艺术陈设品。此器造型简洁却不失庄重，是汝窑瓷器中极为罕见的器型。",
            "cover_image": "https://example.com/porcelain/por_010_0_full.jpg",
            "popularity": 8600,
            "year_range": "1086-1125",
            "origin": "河南宝丰清凉寺",
            "dimensions": "高15.6cm，口径23.5cm",
            "weight": "约1.8kg",
            "collection_place": "北京故宫博物院",
            "tags": ["汝窑", "三足奁", "天青釉", "宋代五大名窑", "官窑"],
            "historical_background": "汝窑位居宋代五大名窑之首，为北宋宫廷烧造御用瓷器。汝官窑遗址1985年在河南省宝丰县清凉寺村被发现。汝窑瓷器以"青如天、面如玉、蝉翼纹、晨星稀"著称，其釉色被誉为"雨过天青云破处"。",
            "cultural_significance": "汝窑瓷器以其"似玉非玉"的质感和含蓄内敛的美学风格，成为中国陶瓷史上难以逾越的高峰。传世汝窑瓷器极为稀少，全世界范围内仅有不足百件，每一件都被各大博物馆视为镇馆之宝。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 340,
        },
        {
            "id": "por_011",
            "name": "宋官窑贯耳瓶",
            "dynasty": "宋",
            "type": "青瓷",
            "material": "瓷",
            "description": "南宋官窑杰作，紫口铁足，釉面开冰裂纹，古朴典雅。",
            "detail_description": "宋官窑贯耳瓶，直口、长颈、颈部两侧置贯耳、圆腹、圈足。通体施灰青色釉，釉面布满深浅不一的冰裂纹片，错落有致，自然天成。官窑瓷器以"紫口铁足"为特征——口部釉层较薄隐约透出胎体的紫色，底部露胎处呈现铁褐色。此器造型古朴庄重，线条挺拔有力，是南宋官窑的典型作品。",
            "cover_image": "https://example.com/porcelain/por_011_0_full.jpg",
            "popularity": 7800,
            "year_range": "1127-1279",
            "origin": "浙江杭州修内司官窑",
            "dimensions": "高26.8cm，口径8.5cm，底径10.2cm",
            "weight": "约2.3kg",
            "collection_place": "北京故宫博物院",
            "tags": ["官窑", "贯耳瓶", "南宋", "冰裂纹", "宋代五大名窑"],
            "historical_background": "南宋官窑是宋室南迁后在杭州设立的御窑，分为修内司官窑和郊坛下官窑两处。官窑瓷器专供宫廷使用，工艺精湛，不计工本。官窑釉面开片是刻意追求的艺术效果，工匠通过控制胎釉膨胀系数的差异，在冷却过程中形成独特的开片纹理。",
            "cultural_significance": "官窑瓷器代表了南宋宫廷审美的高雅格调，其"大巧若拙"的美学理念对后世影响深远。官窑开片纹理的艺术处理，将"缺陷"转化为美学的极致追求，体现了中国传统哲学中"道法自然"的思想。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 280,
        },
        {
            "id": "por_012",
            "name": "宋哥窑鱼耳炉",
            "dynasty": "宋",
            "type": "青瓷",
            "material": "瓷",
            "description": "哥窑名品，金丝铁线开片，鱼耳造型灵动，釉色米黄温润。",
            "detail_description": "宋哥窑鱼耳炉，敞口、束颈、鼓腹、圈足，颈腹部两侧各置鱼形耳。通体施米黄色釉，釉面布满"金丝铁线"开片——黑色大开片纹路中贯穿着金黄色细纹，纵横交错，形成独特的装饰效果。哥窑的"金丝铁线"是工艺上刻意追求的效果，通过染色技术使开片呈现出不同的色彩。底部有支钉烧造的痕迹。",
            "cover_image": "https://example.com/porcelain/por_012_0_full.jpg",
            "popularity": 7400,
            "year_range": "南宋",
            "origin": "浙江龙泉",
            "dimensions": "高10.5cm，口径12.8cm，底径9.5cm",
            "weight": "约0.9kg",
            "collection_place": "北京故宫博物院",
            "tags": ["哥窑", "鱼耳炉", "金丝铁线", "宋代五大名窑", "开片"],
            "historical_background": "哥窑位居宋代五大名窑之一，关于其起源有多个传说。最著名的传说是南宋时期龙泉有章生一、章生二兄弟各主一窑，哥哥的窑口被称为"哥窑"。哥窑最著名的特征就是"金丝铁线"开片，这种装饰技法成为后世仿哥窑瓷器的标志性特征。",
            "cultural_significance": "哥窑瓷器以其独特的开片艺术在陶瓷史上独树一帜。"金丝铁线"将器表的裂纹转化为美的元素，展示了中国古代工匠化朽为奇的艺术智慧，对后世陶瓷美学产生了深远影响。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 260,
        },
        {
            "id": "por_013",
            "name": "宋定窑白釉孩儿枕",
            "dynasty": "宋",
            "type": "白瓷",
            "material": "瓷",
            "description": "定窑白瓷杰作，以孩童为枕座，造型天真可爱，釉色洁白温润。",
            "detail_description": "宋定窑白釉孩儿枕，以孩童侧卧姿态为枕座，孩童双手持一荷叶，荷叶边缘自然卷曲形成枕面。孩童形象丰满圆润，神态安详，衣纹线条流畅。通体施白釉，釉色白中泛黄，俗称"象牙白"。定窑瓷器常用"覆烧"工艺，因此口部往往无釉，称为"芒口"，此器以荷叶边缘巧妙解决了芒口问题。底部有刻字。",
            "cover_image": "https://example.com/porcelain/por_013_0_full.jpg",
            "popularity": 8200,
            "year_range": "960-1127",
            "origin": "河北曲阳涧磁村",
            "dimensions": "高18.3cm，长30cm，宽12.5cm",
            "weight": "约2.5kg",
            "collection_place": "北京故宫博物院",
            "tags": ["定窑", "孩儿枕", "白瓷", "宋代五大名窑", "河北曲阳"],
            "historical_background": "定窑是宋代五大名窑之一，以烧造白瓷闻名于世。窑址位于今河北省曲阳县涧磁村及东西燕山村。定窑创烧于唐代，鼎盛于北宋，元代以后衰落。定窑瓷器以刻花、划花、印花等装饰技法著称，花纹精美。孩儿枕是定窑瓷器中最为著名的作品之一。",
            "cultural_significance": "定窑白瓷代表了宋代北方瓷器的最高水平。孩儿枕不仅是一件实用器，更是一件具有高度艺术价值的雕塑作品，展现了两宋时期世俗生活的温情一面，是中国陶瓷史上少有的以儿童题材为主题的成功作品。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 300,
        },
        {
            "id": "por_014",
            "name": "宋钧窑玫瑰紫釉鼓钉洗",
            "dynasty": "宋",
            "type": "色釉瓷",
            "material": "瓷",
            "description": "钧窑瑰宝，玫瑰紫釉色奇幻瑰丽，窑变效果浑然天成。",
            "detail_description": "宋钧窑玫瑰紫釉鼓钉洗，敞口、浅腹、圈足，口沿和足部各饰一周鼓钉纹。器内外满施玫瑰紫釉，釉色绚丽多变，红紫相间，蓝白交融，宛如夕阳晚霞，美不胜收。钧窑以"窑变"著称，通过控制窑内气氛使釉中的铜、铁等金属元素呈现不同色彩，"入窑一色，出窑万彩"。此器为钧官窑典型作品。",
            "cover_image": "https://example.com/porcelain/por_014_0_full.jpg",
            "popularity": 7600,
            "year_range": "960-1127",
            "origin": "河南禹州",
            "dimensions": "高7.5cm，口径22.8cm，底径13.5cm",
            "weight": "约1.8kg",
            "collection_place": "北京故宫博物院",
            "tags": ["钧窑", "玫瑰紫釉", "鼓钉洗", "宋代五大名窑", "窑变"],
            "historical_background": "钧窑是宋代五大名窑之一，窑址位于今河南省禹州市。钧窑创烧于唐代，宋代达到鼎盛，曾为宫廷烧造御用瓷器。钧窑的铜红釉技术是中国陶瓷史上的一次革命性突破，使瓷器从"南青北白"的格局中突破，开创了多彩瓷器的先河。",
            "cultural_significance": "钧窑"窑变"艺术在中国陶瓷史上具有划时代的意义。它打破了宋代单色釉瓷器的审美定式，以其绚丽多彩的艺术效果独树一帜。钧窑的铜红釉技术为后世红釉瓷器的繁荣奠定了基础。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 270,
        },
        {
            "id": "por_015",
            "name": "宋建窑兔毫盏",
            "dynasty": "宋",
            "type": "黑瓷",
            "material": "瓷",
            "description": "建窑兔毫盏，黑釉中透出兔毫般细纹，宋代斗茶极品。",
            "detail_description": "宋建窑兔毫盏，敞口、斜腹、小圈足，造型简洁。内外施黑釉，釉色乌黑如漆，釉面中透出细密的黄褐色条纹，状如兔毫，故称"兔毫盏"。兔毫纹的形成是由于釉中的铁元素在高温下产生液相分离，形成结晶条纹。宋代盛行斗茶之风，建窑兔毫盏因最宜观察茶色而备受推崇，宋徽宗赵佶在《大观茶论》中特别推崇建窑兔毫盏。",
            "cover_image": "https://example.com/porcelain/por_015_0_full.jpg",
            "popularity": 7100,
            "year_range": "960-1127",
            "origin": "福建建阳水吉镇",
            "dimensions": "高6.8cm，口径12.5cm，底径4.2cm",
            "weight": "约0.4kg",
            "collection_place": "北京故宫博物院",
            "tags": ["建窑", "兔毫盏", "黑釉", "斗茶", "福建建阳"],
            "historical_background": "建窑是宋代著名的黑釉瓷窑场，窑址位于今福建省建阳市水吉镇。建窑创烧于唐代，宋代极盛，元代衰落。建窑瓷器主要以茶盏为主，因宋代斗茶风尚而繁荣。除兔毫盏外，还有油滴盏、曜变盏等名贵品种。",
            "cultural_significance": "建窑兔毫盏是中国黑釉瓷器的杰出代表，不仅在中国陶瓷史上占据重要地位，对日本茶道文化也产生了极为深远的影响。日本将建窑茶盏称为"天目盏"，视若珍宝。其中最为珍贵的"曜变天目"被日本列为国宝。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 290,
        },
        {
            "id": "por_016",
            "name": "明德化窑白釉观音坐像",
            "dynasty": "明",
            "type": "白瓷",
            "material": "瓷",
            "description": "德化白瓷极品，"中国白"之誉，观音慈悲庄严，衣纹飘逸。",
            "detail_description": "明德化窑白釉观音坐像，观音菩萨善跏趺坐于莲台之上，头戴宝冠，面容慈祥端庄，双目微垂，嘴角含笑。身着天衣，衣纹线条流畅飘逸，如行云流水。通体施白釉，釉色乳白温润如凝脂，俗称"猪油白"。德化白瓷以其独特的瓷质和温润的釉色被誉为"中国白"，此像为德化瓷塑宗师何朝宗的代表作品。背部有"何朝宗"葫芦形印款。",
            "cover_image": "https://example.com/porcelain/por_016_0_full.jpg",
            "popularity": 8300,
            "year_range": "明代中期",
            "origin": "福建德化",
            "dimensions": "高48.5cm，底座宽18.5cm",
            "weight": "约4.8kg",
            "collection_place": "北京故宫博物院",
            "tags": ["德化窑", "何朝宗", "白釉", "观音", "福建德化"],
            "historical_background": "德化窑位于福建省德化县，宋元时期开始烧造白瓷，明代达到鼎盛。德化白瓷以其胎质洁白细腻、釉色温润如玉而闻名世界。明代德化瓷塑大师何朝宗（约1522-1600）将德化瓷塑艺术推向了巅峰，其作品被誉为"东方艺术之瑰宝"。",
            "cultural_significance": "德化白瓷是中国陶瓷史上一个独特的艺术流派，其瓷塑艺术具有极高的艺术价值。"中国白"（Blanc de Chine）是法国人对德化白瓷的美誉。德化白瓷自明代起大量出口欧洲，对欧洲瓷器工艺产生了重要影响。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 310,
        },
        {
            "id": "por_017",
            "name": "宋磁州窑白地黑花龙凤纹罐",
            "dynasty": "宋",
            "type": "白地黑花",
            "material": "瓷",
            "description": "磁州窑典型作品，白地黑花对比强烈，绘画笔法豪放洒脱。",
            "detail_description": "宋磁州窑白地黑花龙凤纹罐，直口、短颈、丰肩、鼓腹、圈足。器身以白釉为地，以黑彩绘龙凤穿云纹，纹饰线条粗犷豪放，黑白对比强烈，具有鲜明的民间艺术特色。磁州窑的白地黑花工艺属于釉下彩绘，在施白色化妆土的胎体上用黑彩绘制纹饰，再施透明釉烧制而成。这种风格对后世青花瓷的发展产生了重要影响。",
            "cover_image": "https://example.com/porcelain/por_017_0_full.jpg",
            "popularity": 6500,
            "year_range": "960-1127",
            "origin": "河北磁县观台镇",
            "dimensions": "高35.2cm，口径15.8cm，底径17.5cm",
            "weight": "约4.2kg",
            "collection_place": "上海博物馆",
            "tags": ["磁州窑", "白地黑花", "龙凤纹", "宋代", "河北磁县"],
            "historical_background": "磁州窑是宋代北方最大的民间瓷窑体系，窑址以今河北省磁县观台镇为中心，影响遍及河南、山西、山东等地。磁州窑以白地黑花、刻划花、珍珠地等装饰技法著称，产品种类丰富，风格质朴豪放。",
            "cultural_significance": "磁州窑虽然不被列入宋代"五大名窑"，但作为民间瓷窑的杰出代表，其自由奔放的艺术风格和丰富的装饰技法对后世影响深远。磁州窑的白地黑花工艺直接影响了元代青花瓷的审美取向。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 240,
        },
        {
            "id": "por_018",
            "name": "唐越窑青釉刻花执壶",
            "dynasty": "唐",
            "type": "青瓷",
            "material": "瓷",
            "description": "越窑青瓷精品，"类玉类冰"之誉，刻花技法精湛。",
            "detail_description": "唐越窑青釉刻花执壶，撇口、长颈、圆腹、圈足，一侧置流（壶嘴），另一侧置柄（把手）。通体施青釉，釉色青绿温润，"类玉类冰"。壶身刻有花卉纹饰，刀法流畅犀利，线条婉转自如。越窑青瓷被誉为"千峰翠色"、"如冰似玉"，是唐代最负盛名的青瓷品种。唐代诗人陆龟蒙有诗赞曰："九秋风露越窑开，夺得千峰翠色来。"",
            "cover_image": "https://example.com/porcelain/por_018_0_full.jpg",
            "popularity": 6900,
            "year_range": "618-907",
            "origin": "浙江余姚上林湖",
            "dimensions": "高22.3cm，口径6.8cm，底径10.2cm",
            "weight": "约1.5kg",
            "collection_place": "浙江省博物馆",
            "tags": ["越窑", "青瓷", "执壶", "唐代", "浙江余姚"],
            "historical_background": "越窑是中国最早的瓷窑之一，创烧于东汉，鼎盛于唐、五代，窑址以浙江余姚上林湖为中心。越窑青瓷代表了唐代青瓷的最高水平，曾作为"秘色瓷"进贡宫廷。越窑的烧造历史长达一千多年，是中国陶瓷史上延续时间最长的瓷窑体系。",
            "cultural_significance": "越窑青瓷在中国陶瓷史上具有开创性地位，它奠定了中国"南青北白"的陶瓷格局。越窑的"秘色瓷"是唐代宫廷用瓷的巅峰之作，法门寺地宫出土的秘色瓷证实了文献记载的真实性。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 260,
        },
        {
            "id": "por_019",
            "name": "唐长沙窑青釉褐彩诗文壶",
            "dynasty": "唐",
            "type": "釉下彩",
            "material": "瓷",
            "description": "长沙窑首创釉下彩绘，诗文与瓷器的完美结合，唐代外销瓷代表。",
            "detail_description": "唐长沙窑青釉褐彩诗文壶，撇口、短颈、圆腹、平底，多棱短流。壶身以褐彩书写唐代诗人诗句，诗文与瓷器巧妙结合，开创了中国陶瓷题诗装饰的先河。长沙窑釉下彩绘技术是陶瓷史上的一次重要革命，它突破了越窑、邢窑单色釉的传统，为后世釉下彩瓷（青花、釉里红等）的发展奠定了基础。长沙窑瓷器大量出口到中东、东南亚等地。",
            "cover_image": "https://example.com/porcelain/por_019_0_full.jpg",
            "popularity": 6200,
            "year_range": "618-907",
            "origin": "湖南长沙铜官窑",
            "dimensions": "高20.5cm，口径8.3cm，底径12.5cm",
            "weight": "约1.8kg",
            "collection_place": "湖南省博物馆",
            "tags": ["长沙窑", "釉下彩", "诗文壶", "唐代", "湖南长沙"],
            "historical_background": "长沙窑是唐代著名的外销瓷窑场，窑址位于今湖南省长沙市望城区铜官镇。长沙窑首创釉下多彩工艺，突破了传统的单色釉和刻划花装饰。长沙窑的装饰题材丰富多样，包括诗文、绘画、贴花等，是中国陶瓷装饰史上的一座里程碑。",
            "cultural_significance": "长沙窑釉下彩绘技术的发明是中国陶瓷史上的重大突破，为宋元时期釉下彩瓷的繁荣奠定了技术基础。长沙窑的海外贸易规模宏大，在东南亚、中东、非洲等地都有长沙窑瓷器出土，是"海上丝绸之路"的重要见证。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 250,
        },
        {
            "id": "por_020",
            "name": "唐三彩骆驼载乐俑",
            "dynasty": "唐",
            "type": "三彩",
            "material": "陶",
            "description": "唐三彩杰作，骆驼载乐俑生动再现了盛唐丝绸之路的文化交融。",
            "detail_description": "唐三彩骆驼载乐俑，双峰骆驼昂首站立于长方形平板上，驼背上铺有圆垫，垫上有一组乐舞俑共八人，包括七名乐师和一名舞者。乐师手持琵琶、箜篌、筚篥、笛子等乐器，舞者在中央翩翩起舞。骆驼体态雄健，造型写实。三彩釉色以黄、绿、白为主，色彩斑斓。此器出土于陕西西安，是盛唐时期中外文化交流的生动写照。",
            "cover_image": "https://example.com/porcelain/por_020_0_full.jpg",
            "popularity": 8700,
            "year_range": "618-907",
            "origin": "陕西西安",
            "dimensions": "高58.4cm，长43cm",
            "weight": "约8.5kg",
            "collection_place": "中国国家博物馆",
            "tags": ["唐三彩", "骆驼", "乐俑", "丝绸之路", "唐代"],
            "historical_background": "唐三彩是唐代低温铅釉陶器的统称，因以黄、绿、白三种颜色为主而得名。唐三彩创烧于唐代高宗时期，开元年间达到鼎盛。唐三彩主要用作冥器（随葬品），是唐代厚葬之风的产物。唐三彩的造型题材极为丰富，包括人物、动物、器皿、建筑等。",
            "cultural_significance": "唐三彩是中国陶瓷史上的一颗璀璨明珠，它以独特的造型艺术和绚丽的色彩著称于世。唐三彩是盛唐气象的生动体现，展现了唐代社会的繁荣、开放和多元文化交融。唐三彩对后来辽三彩、宋三彩以及日本奈良三彩都产生了重要影响。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 300,
        },
        {
            "id": "por_021",
            "name": "宋景德镇青白釉刻花梅瓶",
            "dynasty": "宋",
            "type": "青白瓷",
            "material": "瓷",
            "description": "青白瓷介于青白之间，"影青"之美，刻花若隐若现。",
            "detail_description": "宋景德镇青白釉刻花梅瓶，小口、短颈、丰肩、瘦底、圈足。通体施青白釉，釉色介于青白之间，青中带白、白中透青，俗称"影青"。瓶身刻有缠枝花卉纹，刻纹深处釉色较深，浅处釉色较淡，形成深浅变化的效果。青白瓷的胎体轻薄细腻，在光照下可透见瓶身的纹饰，"影青"之名由此而来。",
            "cover_image": "https://example.com/porcelain/por_021_0_full.jpg",
            "popularity": 6700,
            "year_range": "960-1127",
            "origin": "江西景德镇",
            "dimensions": "高35.8cm，口径5.5cm，底径11.2cm",
            "weight": "约1.5kg",
            "collection_place": "北京故宫博物院",
            "tags": ["青白瓷", "影青", "景德镇", "梅瓶", "宋代"],
            "historical_background": "青白瓷是宋代景德镇窑创烧的瓷器新品种，宋代称"青白瓷"，清代以后俗称"影青"。青白瓷的釉色得益于景德镇优质的瓷石原料和先进的制瓷工艺。青白瓷的胎体采用"二元配方"（瓷石加高岭土），使胎体更加洁白坚致。",
            "cultural_significance": "青白瓷在宋代风靡一时，不仅行销国内，还大量出口海外。景德镇青白瓷的工艺成就为元代青花瓷和明清彩瓷的繁荣奠定了坚实的基础。青白瓷的"薄如纸、白如玉、明如镜、声如磬"的审美特征影响了中国陶瓷近千年。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 240,
        },
        {
            "id": "por_022",
            "name": "元枢府釉刻花盘",
            "dynasty": "元",
            "type": "卵白釉",
            "material": "瓷",
            "description": "元代枢府釉瓷器，卵白釉色温润含蓄，为元代官用瓷器。",
            "detail_description": "元枢府釉刻花盘，敞口、浅腹、圈足。通体施卵白釉，釉色白中泛青，如鹅卵之色，温润含蓄。盘心刻有花卉纹饰，内壁印有"枢府"二字款。枢府釉是元代景德镇为枢密院（元代最高军事机构）烧造的官用瓷器，是明代官窑制度的前身。枢府釉瓷器造型规整，胎体厚重，不同于宋代瓷器的轻薄精致。",
            "cover_image": "https://example.com/porcelain/por_022_0_full.jpg",
            "popularity": 5800,
            "year_range": "1271-1368",
            "origin": "江西景德镇",
            "dimensions": "高5.2cm，口径20.8cm，底径12.5cm",
            "weight": "约1.2kg",
            "collection_place": "上海博物馆",
            "tags": ["枢府釉", "卵白釉", "元代", "景德镇", "官用瓷"],
            "historical_background": "枢府釉是元代景德镇创烧的卵白釉瓷器品种，因印有"枢府"二字而得名。元朝在景德镇设立"浮梁瓷局"管理官窑生产，枢府釉瓷器即为官府定烧之器。枢府釉的烧造为元代青花瓷和明清官窑制度的建立起到了承前启后的作用。",
            "cultural_significance": "枢府釉瓷器是元代陶瓷史上一个承前启后的重要品种，它连接了宋代单色釉传统与元代彩瓷创新。枢府釉的工艺技术为明代永乐甜白瓷的烧造奠定了技术基础。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 200,
        },
        {
            "id": "por_023",
            "name": "元釉里红缠枝菊纹玉壶春瓶",
            "dynasty": "元",
            "type": "釉里红",
            "material": "瓷",
            "description": "釉里红名品，铜红发色纯正，缠枝菊纹舒展流畅。",
            "detail_description": "元釉里红缠枝菊纹玉壶春瓶，撇口、细颈、垂腹、圈足。通体以釉里红绘制缠枝菊纹，釉里红发色鲜艳纯正，红白相映，格外醒目。釉里红是以氧化铜为着色剂在釉下绘彩，高温一次烧成，铜红发色对窑温和气氛极为敏感，"要想红，必火中求"，烧制难度极大。玉壶春瓶为经典酒器造型，"玉壶买春"典出唐代诗句。",
            "cover_image": "https://example.com/porcelain/por_023_0_full.jpg",
            "popularity": 7000,
            "year_range": "1271-1368",
            "origin": "江西景德镇",
            "dimensions": "高30.5cm，口径7.8cm，底径9.5cm",
            "weight": "约1.6kg",
            "collection_place": "北京故宫博物院",
            "tags": ["釉里红", "元代", "玉壶春瓶", "铜红", "景德镇"],
            "historical_background": "釉里红是元代景德镇继青花之后创烧的又一重要釉下彩品种。元代工匠成功掌握了铜红的还原技术，使釉里红瓷器得以问世。釉里红的烧制比青花困难得多，因此元代釉里红存世量远少于青花，更加珍贵。",
            "cultural_significance": "釉里红在中国陶瓷史上具有重要地位，它开创了铜红釉下彩的先河。明代永乐、宣德时期的宝石红釉和清代康熙郎窑红的成功，都是建立在元代釉里红技术基础之上的。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 250,
        },
        {
            "id": "por_024",
            "name": "明永乐青花海水龙纹扁壶",
            "dynasty": "明",
            "type": "青花瓷",
            "material": "瓷",
            "description": "永乐青花巅峰之作，海水龙纹气势磅礴，苏麻离青料沉入胎骨。",
            "detail_description": "明永乐青花海水龙纹扁壶，洗口、束颈、扁圆腹、圈足，腹部两侧有双耳。器身以青花绘制海水龙纹，惊涛骇浪之中，巨龙腾空而起，气势磅礴。青花用料为进口"苏麻离青"（苏勃泥青），含铁量高而含锰量低，发色浓艳深沉，釉面有自然形成的铁锈斑。永乐青花瓷器造型新颖多样，纹饰繁复精细，代表了明代青花瓷的最高水平。",
            "cover_image": "https://example.com/porcelain/por_024_0_full.jpg",
            "popularity": 9100,
            "year_range": "1403-1424",
            "origin": "江西景德镇",
            "dimensions": "高48.2cm，口径8.6cm，底径16.5cm",
            "weight": "约6.5kg",
            "collection_place": "北京故宫博物院",
            "tags": ["明永乐", "青花", "海水龙纹", "扁壶", "苏麻离青"],
            "historical_background": "明永乐时期是青花瓷发展的黄金时代。永乐皇帝朱棣派遣郑和七下西洋，带回了优质的钴料"苏麻离青"。永乐御窑厂在督陶官的管理下，精益求精，烧造了大量精美的青花瓷器。永乐青花纹饰题材广泛，包括龙凤纹、花卉纹、海水纹、人物故事等。",
            "cultural_significance": "永乐青花瓷是中国青花瓷史上的一座高峰，被后世誉为"青花之王"。其独特的"苏麻离青"发色效果成为后世追求、模仿的经典。永乐青花瓷在当时就作为国礼赠送给外国使节，是"海上丝绸之路"的重要见证。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 330,
        },
        {
            "id": "por_025",
            "name": "清雍正粉彩过枝牡丹纹碗",
            "dynasty": "清",
            "type": "粉彩",
            "material": "瓷",
            "description": "雍正粉彩极品，"过枝"画法出神入化，色彩淡雅宜人。",
            "detail_description": "清雍正粉彩过枝牡丹纹碗，敞口、深腹、圈足。碗内外以粉彩绘过枝牡丹纹，花枝从碗外壁延伸至内壁，"过枝"画法巧妙而富有情趣。粉彩色彩柔和淡雅，色调过渡自然，有"雍正粉彩以雅取胜"之誉。雍正粉彩以玻璃白打底，使色彩呈现出粉润柔和的质感。底部有"大清雍正年制"六字双行楷书款，工整规范。",
            "cover_image": "https://example.com/porcelain/por_025_0_full.jpg",
            "popularity": 8400,
            "year_range": "1723-1735",
            "origin": "江西景德镇",
            "dimensions": "高6.8cm，口径15.3cm，底径6.2cm",
            "weight": "约0.35kg",
            "collection_place": "北京故宫博物院",
            "tags": ["雍正", "粉彩", "过枝牡丹", "碗", "景德镇"],
            "historical_background": "粉彩瓷在雍正时期达到了工艺和艺术的巅峰。雍正皇帝本人对瓷器制作极为关注，常亲自审定瓷器样式。雍正粉彩以其淡雅柔和的格调著称，与乾隆粉彩的富丽堂皇形成鲜明对比。"过枝"画法是雍正粉彩中极具特色的一种装饰技法，起源于清初。",
            "cultural_significance": "雍正粉彩代表了清代粉彩瓷器的最高艺术成就，被誉为"瓷器上的工笔画"。其"淡雅、含蓄、精致"的艺术风格体现了雍正皇帝的个人审美趣味，是中国传统文人审美在陶瓷艺术中的完美呈现。",
            "image_count": 5,
            "audio_narrator": "博物馆专业讲解员",
            "audio_duration": 280,
        },
    ]

    db = SessionLocal()
    try:
        existing = db.query(Artwork).count()
        if existing > 0:
            print(f"数据库已有 {existing} 条文物记录，跳过导入")
            return

        for data in artworks_data:
            artwork = Artwork(
                id=data["id"],
                name=data["name"],
                dynasty=data["dynasty"],
                type=data["type"],
                material=data["material"],
                description=data["description"],
                detail_description=data["detail_description"],
                cover_image=data["cover_image"],
                popularity=data["popularity"],
                like_count=int(data["popularity"] * 0.35),
                favorite_count=int(data["popularity"] * 0.25),
                comment_count=int(data["popularity"] * 0.08),
                year_range=data["year_range"],
                origin=data["origin"],
                dimensions=data["dimensions"],
                weight=data["weight"],
                collection_place=data["collection_place"],
                tags=data["tags"],
                historical_background=data["historical_background"],
                cultural_significance=data["cultural_significance"],
                create_time=datetime.now(),
            )
            db.add(artwork)
            db.flush()

            # 创建图片
            for i in range(data.get("image_count", 5)):
                img = ArtworkImage(
                    id=f"{data['id']}_img_{i}",
                    artwork_id=data["id"],
                    url=f"https://example.com/porcelain/{data['id']}_{i}_full.jpg",
                    thumbnail_url=f"https://example.com/porcelain/{data['id']}_{i}_thumb.jpg",
                    title=f"{data['name']} - {'正面' if i == 0 else f'细节{i}'}",
                    description="主视图" if i == 0 else f"局部特写{i}",
                    width=1200 if i == 0 else 800,
                    height=1600 if i == 0 else 800,
                )
                db.add(img)

            # 创建音频导览
            audio = AudioGuide(
                id=f"{data['id']}_audio",
                artwork_id=data["id"],
                url=f"https://example.com/audio/{data['id']}_guide.mp3",
                duration=data.get("audio_duration", 240),
                narrator=data.get("audio_narrator", "博物馆专业讲解员"),
                text_script=data["detail_description"][:500],
            )
            db.add(audio)

        db.commit()
        print(f"成功导入 {len(artworks_data)} 件文物数据")

    except Exception as e:
        db.rollback()
        print(f"导入失败: {e}")
        raise
    finally:
        db.close()


def seed_admin_user():
    """创建默认管理员用户"""
    db = SessionLocal()
    try:
        existing = db.query(User).filter(User.account == "admin").first()
        if existing:
            print("管理员用户已存在，跳过")
            return

        user = User(
            account="admin",
            password=hash_password("admin123"),
            nickname="管理员",
            phone="13800000000",
            email="admin@museum.com",
        )
        db.add(user)
        db.commit()
        print(f"创建管理员用户: admin / admin123")

        demo = User(
            account="demo",
            password=hash_password("demo123"),
            nickname="演示用户",
            phone="13900000000",
            email="demo@museum.com",
            signature="热爱中国传统文化",
        )
        db.add(demo)
        db.commit()
        print(f"创建演示用户: demo / demo123")

    except Exception as e:
        db.rollback()
        print(f"创建用户失败: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    print("=" * 50)
    print("掌上博物馆 - 数据初始化")
    print("=" * 50)

    # 创建表
    Base.metadata.create_all(bind=engine)
    print("数据库表创建完成")

    # 导入文物数据
    seed_artworks()

    # 创建用户
    seed_admin_user()

    print("=" * 50)
    print("初始化完成！")
    print("管理员账号: admin / admin123")
    print("演示账号:   demo / demo123")
    print("=" * 50)
